### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by 57ar7up** [Aakash1312/scroll-searcher#13] opened 2016-11-18 11:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Unknown Windows Version
**Thrown From**: [scroll-searcher](https://github.com/Aakash1312/scroll-searcher) package, v5.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /%USERPROFILE%/.atom/packages/scroll-searcher/lib/main.coffee:99

TypeError: Cannot read property 'mainModule' of undefined
    at Main.hide (file:///%USERPROFILE%/.atom/packages/scroll-searcher/lib/main.coffee:56:20)
    at Main.hide (file:///%USERPROFILE%/.atom/packages/scroll-searcher/lib/main.coffee:1:1)
    at atom-workspace.subs.add.atom.commands.add.core:cancel (file:///%USERPROFILE%/.atom/packages/scroll-searcher/lib/main.coffee:49:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\57ar7\AppData\Local\atom\app-1.12.4\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -1:52 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:52 core:cancel (atom-text-editor.editor.is-focused)
     -1:51.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:51.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:50.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:50.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:47.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:47.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:29.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:29.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:24.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:21.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 72x -0:12.4.0 core:cancel (div.panels-item)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "latex",
      "linter",
      "platformio-ide",
      "nuclide",
      "filecolor",
      "project-colorize",
      "highlight-column",
      "highlight-line",
      "build-tools",
      "autohide-tree-view",
      "editor-background",
      "lazy-motion",
      "linter-gcc",
      "atom-less",
      "build",
      "linter-less",
      "markdown-scroll-sync",
      "linter-scalac",
      "platformio-ide-terminal",
      "pigments",
      "dartlang",
      "tool-bar",
      "abstract-machine",
      "abstract-machine-mips",
      "audio",
      "git-control",
      "keyboard-sounds",
      "autocomplete-json",
      "autocomplete-modules",
      "git-diff-details",
      "editorconfig",
      "latexer",
      "symbols-tree-view",
      "character-table",
      "atom-toolbar"
    ],
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
abstract-machine, v0.1.0 (inactive)
abstract-machine-mips, v0.1.0 (inactive)
activate-power-mode, v1.1.0 (active)
advanced-open-file, v0.16.4 (inactive)
an-color-picker, v1.0.2 (inactive)
atom-beautify, v0.29.13 (active)
atom-bracket-highlight, v0.3.1 (active)
atom-jade, v0.3.0 (active)
atom-json-color, v0.4.2 (active)
atom-less, v0.1.10 (inactive)
atom-toolbar, v0.1.6 (inactive)
audio, v1.5.6 (inactive)
auto-detect-indentation, v1.3.0 (active)
auto-indent, v0.5.0 (active)
auto-indent-file, v0.2.0 (inactive)
autocomplete-clang, v0.10.0 (active)
autocomplete-json, v5.1.0 (inactive)
autocomplete-modules, v1.6.7 (inactive)
autohide-tree-view, v0.25.1 (inactive)
build, v0.67.0 (inactive)
build-npm-apm, v0.12.0 (active)
build-tools, v4.5.4 (inactive)
busy, v0.7.0 (active)
character-table, v0.4.3 (inactive)
color-tabs, v0.1.8 (active)
command-toolbar, v1.0.12 (active)
convert-to-utf8, v0.2.4 (inactive)
dark-flat-ui, v1.2.4 (inactive)
dartlang, v0.6.45 (inactive)
dev-tools-themes, v0.1.3 (active)
editor-background, v1.2.27 (inactive)
editorconfig, v2.0.5 (inactive)
environment, v1.3.1 (active)
extract-web, v0.3.2 (inactive)
file-icons, v1.7.25 (active)
filecolor, v0.4.0 (inactive)
filesize, v2.0.0 (active)
fonts, v1.7.0 (active)
gcc-make-run, v0.2.9 (active)
git-control, v0.8.2 (inactive)
git-diff-details, v1.4.0 (inactive)
git-time-machine, v1.5.4 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
guess-indent, v0.1.0 (inactive)
highlight-column, v0.5.1 (inactive)
highlight-line, v0.11.1 (inactive)
highlight-selected, v0.11.2 (active)
html-entities, v0.4.0 (active)
hyperclick, v0.0.39 (active)
jade-autocompile, v0.8.3 (active)
keyboard-scroll, v0.4.0 (active)
keyboard-sounds, v0.2.0 (inactive)
language-autohotkey, v0.1.0 (active)
language-autoit, v0.2.1 (active)
language-avisynth, v0.6.0 (active)
language-awk, v0.1.11 (active)
language-batch, v0.3.3 (active)
language-cmake, v0.2.0 (active)
language-csv, v1.1.2 (active)
language-cuda, v0.1.0 (active)
language-diff, v0.6.0 (active)
language-generic-config, v1.2.0 (active)
language-glsl, v2.0.1 (active)
language-hcl, v0.4.0 (active)
language-hlsl, v1.2.0 (active)
language-htaccess, v0.1.1 (active)
language-ignore, v1.5.2 (active)
language-ini, v1.16.0 (active)
language-log, v1.6.0 (active)
language-lua, v0.9.11 (active)
language-matlab, v0.2.1 (active)
language-mediawiki, v2.2.0 (active)
language-openscad, v0.4.3 (active)
language-pascal, v0.18.1 (active)
language-patch, v1.2.0 (active)
language-powershell, v4.0.0 (active)
language-pseudo, v0.1.3 (active)
language-reg, v0.0.0 (active)
language-scala, v1.1.8 (active)
language-svg, v0.9.0 (active)
language-tmux, v0.4.0 (active)
language-vbscript, v0.7.0 (active)
language-viml, v1.1.2 (active)
language-x86asm, v0.8.0 (active)
latex, v0.40.0 (inactive)
latex-completions, v0.3.2 (active)
latexer, v0.3.0 (inactive)
latextools, v0.8.5 (active)
lazy-motion, v0.4.0 (inactive)
linter, v1.11.18 (inactive)
linter-gcc, v0.6.15 (inactive)
linter-less, v2.6.0 (inactive)
linter-matlab, v1.1.0 (active)
linter-scalac, v1.4.2 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
minimap, v4.25.6 (active)
minimap-autohide, v0.10.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
new-tab, v0.5.3 (active)
npm-install, v4.0.3 (inactive)
npm-plus, v0.4.0 (inactive)
nuclide, v0.182.0 (inactive)
nvatom, v0.11.0 (active)
on-save, v0.2.10 (active)
one-tab, v0.10.0 (active)
open-in, v4.0.0 (inactive)
open-in-browsers, v0.0.19 (active)
open-sesame, v0.5.0 (active)
outlander-syntax, v1.1.0 (inactive)
outlander-ui, v1.3.1 (inactive)
php-cs-fixer, v2.5.9 (active)
pigments, v0.37.0 (inactive)
platformio-ide, v1.6.0 (inactive)
platformio-ide-terminal, v2.2.2 (inactive)
processing, v0.13.0 (inactive)
project-colorize, v0.2.0 (inactive)
python-tools, v0.6.8 (active)
qolor, v0.4.1 (active)
rainbow-tabs, v2.2.1 (active)
sass-autocompile, v0.13.1 (active)
scroll-searcher, v5.0.0 (active)
scroll-sync, v0.1.5 (inactive)
set-syntax, v0.3.2 (active)
split-diff, v1.0.6 (inactive)
svg-preview, v0.10.0 (active)
symbols-tree-view, v0.13.2 (inactive)
synced-sidebar, v0.4.3 (active)
texter, v0.1.0 (active)
tool-bar, v1.0.1 (inactive)
trailing-spaces, v0.3.2 (active)
tree-view-autoresize, v1.3.0 (active)
tree-view-git-status, v1.2.0 (active)
video-player, v2.2.0 (inactive)
wordcount, v2.8.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Aakash1312** [comment] 2016-11-21 15:47
I think the bug is related to upgrade of find-and-replace API. I'll look into the matter. Thanks for your feedback @57ar7up

**Comment by Aakash1312** [comment] 2016-11-25 13:24
I'm sorry @57ar7up I am unable to reproduce the problem. Can you please tell me steps to reproduce the problem?

**Comment by 57ar7up** [comment] 2016-11-25 19:45
It's appears when I press Escape

**Comment by Aakash1312** [comment] 2016-12-01 16:04
@57ar7up Does the bug appear every time u press Escape or only at some instances. And if later is the case, the can you please elaborate it?

**Comment by crstnbr** [comment] 2017-01-09 22:01
I do have the same bug and it appears every time I press Escape.

**Comment by Aakash1312** [comment] 2017-01-22 05:06
I think the error comes when you press escape before activating the find-and-replace atleast once. Correct me if I am wrong

**Comment by 57ar7up** [comment] 2017-01-22 14:30
Yes

**Comment by Aakash1312** [comment] 2017-01-22 14:48
I got the problem. I'll be working on it. Thanks for the feedback :)

**Comment by Aakash1312** [comment] 2017-01-25 18:20
Scroll searcher has been updated. Due to recent shadow dom update, this new version will only work with Atom >= v1.13.0.
https://atom.io/packages/scroll-searcher

**Comment by Aakash1312** [comment] 2017-01-26 19:21
I am closing the issue. Please reopen the issue if required.

**Closed by Aakash1312** 2017-01-26 19:21 UTC
